- name: add libselinux-python
  sudo: yes
  yum: name=libselinux-python state=installed

- name: add yum.repository remi
  sudo: yes
  yum: name={{item}} state=installed
  with_items:
      - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: replace file about remi.repo
  copy: src=remi.repo dest=/etc/yum.repos.d/ mode=664

- name: install dos2unix
  sudo: yes
  yum: name={{item.name}} state=installed
  with_items:
      - {name: dos2unix}

